# Generated by Django 5.0.2 on 2025-04-20 20:20

import django.core.validators
import stu_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureresource',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='lecture_resources/'),
        ),
        migrations.AddField(
            model_name='lectureresource',
            name='lecture',
            field=models.FileField(blank=True, null=True, upload_to='lecture_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi']), stu_profile.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='lectureresource',
            name='video_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lectureresource',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video_thumbnails/'),
        ),
    ]
